
<!-- Start: login-holder -->
<div id="registro-holder">

	<!-- start logo -->
	<div id="logo-registro">

	</div>
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="registrobox">
	
	<!--  start login-inner -->
	<div id="registro-inner">
		<form  method="post">
		<table border="0" cellpadding="4" cellspacing="4" width="540">
		<tr>
			<th>Nacionalidad :</th>
			<td><input type="text"  id="nacionalidad"  name="nacionalidad"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Tipo Documento:</th>
			<td><input type="text"  id="tipoDocumento"  name="tipoDocumento"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Nro. Documento :</th>
			<td><input type="text"  id="nroDocumento"  name="nroDocumento"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Empresa:</th>
			<td><input type="text"  id="empresa"  name="empresa"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Representate Legal :</th>
			<td><input type="text"  id="representanteLegal"  name="representanteLegal"  class="registro-inp" /></td>
		</tr>
                <tr>
			<th>Telefono:</th>
			<td><input type="text"  id="telefono"  name="telefono"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Email :</th>
			<td><input type="text"  id="email"  name="email"  class="registro-inp" /></td>
		</tr>
		<tr>
			<th>Clave :</th>
			<td><input type="text"  id="clave"  name="clave"  class="registro-inp" /></td>
		</tr>
		
		
		<tr>
			<th></th>
			<td valign="top">
                        </td>
		</tr>
		<tr>
			<th></th>
                        <td >
                            <input type="button" class="button medium blue"  value="Login"
                                   onclick="window.location='/admin/'"/>
                            <input type="button" class="button medium blue"   value="Guarda Datos"  
                                   onclick="window.location='/default/registro/'">
                        </td>
		</tr>
		</table>
		</form>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	 
    </div>
 <!--  end loginbox -->
 
	<!--  start forgotbox ................................................................................... -->
	
	<!--  end forgotbox -->

</div>
<!-- End: login-holder -->
