<!DOCTYPE html>
<html>
    <head>
        <title> SOFTEIN - REPORT</title>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    
    </head>
    <body>
        <h5>CONVOCATORIA : <?php echo $this->empresas[0]['proceso'];?>  </h5>
        <h7> Fecha de Convocatoria: <?php echo $this->empresas[0]['fecha'];?> </h7><br>
        <h7> Fecha de Cierre: <?php echo $this->empresas[0]['limite'];?> </h7>
        _____________________________________________________________________________________________
        <br>
        <h3></h3>
        <?php 
        $idConvocatoria = $this->empresas[0]['idConvocatoria'];
        $lista_colores=array('#E0FFFF','#F8F8FF'); 
        $num_colores=2; 
        $indice=0; 
        
        foreach ($this->empresas as $value) :
        $color = $lista_colores[$indice % $num_colores];
        $indice++;    
        
        $modelExperiencia = new App_Model_Experiencia();
        $experienciaEmpresa = $modelExperiencia->experienciaEmpresa($value['idEmpresa']);
        $experienciaEspecifica = $modelExperiencia->experienciaEspecifica($value['idEmpresa']);
        
       /* ======= EXPERIENCIA GENERAL ANIOS MESES =========== */
        $tiempo = $modelExperiencia->tiempo($value['idEmpresa']);
        $anio = 0;
        $meses = 0;
        for ($t = 0; $t < count($tiempo); $t++) {
            $datetime1 = new DateTime($tiempo[$t]['fechaInicio']);
            $datetime2 = new DateTime($tiempo[$t]['fechaFin']);
            $interval = $datetime1->diff($datetime2);
            $anio+= $interval->format('%Y');

            $intervalMeses = $datetime1->diff($datetime2);
            $meses+= $intervalMeses->format('%M');

            }
            if($meses>12){
                $meses = $meses/12;
                $total = round($meses, 1, PHP_ROUND_HALF_UP);
                $partes = explode(".", $total);
                $anio += $partes[0];
                $meses = $partes[1];
           }
           
       /* ======= EXPERIENCIA ESPECIFICA ANIOS MESES =========== */
        $tiempoEspecifica = $modelExperiencia->tiempoExperienciaEspecifica($value['idEmpresa']);
        $anioEspecifica = 0;
        $mesesEspecifica = 0;
        for ($te = 0; $te < count($tiempoEspecifica); $te++) {
            $datetime1 = new DateTime($tiempoEspecifica[$te]['fechaInicio']);
            $datetime2 = new DateTime($tiempoEspecifica[$te]['fechaFin']);
            $interval = $datetime1->diff($datetime2);
            $anioEspecifica+= $interval->format('%Y');

            $intervalMeses = $datetime1->diff($datetime2);
            $mesesEspecifica+= $intervalMeses->format('%M');

            }
            if($mesesEspecifica>12){
                $mesesEspecifica = $mesesEspecifica/12;
                $totalEspecifico = round($mesesEspecifica, 1, PHP_ROUND_HALF_UP);
                $partesEspecifica = explode(".", $total);
                $anioEspecifica += $partesEspecifica[0];
                $mesesEspecifica = $partesEspecifica[1];
           }
           
           
           
        /* ========================= INICIO  =================*/   
        $experienciaEmpresa[0]['experienciaGeneralEmpresa'] = $anio;
        /* ========================= FIN  =================*/   
        
        $experienciaEspecifica[0]['experienciaEspecificaEmpresa'] = $anioEspecifica;
        
        
        $aniosExperienciaDiferencia = $value['aniosExperiencia'] - $this->criterioEvaluacion['antiguedadEmpresa'];  
        $aniosExperienciaGeneralDiferencia =  $experienciaEmpresa[0]['experienciaGeneralEmpresa'] - $this->criterioEvaluacion['experienciaGeneralAnos'];
        $mesesExperienciaGeneralDiferencia =  $meses - $this->criterioEvaluacion['experienciaGeneralMeses'];
       
        $aniosExperienciaEspecificaDiferencia = $experienciaEspecifica[0]['experienciaEspecificaEmpresa'] - $this->criterioEvaluacion['experienciaEspecificaAnos'];
        $mesesExperienciaEspecificaDiferencia = $mesesEspecifica - $this->criterioEvaluacion['experienciaEspecificaMeses'];
        $montoFacturadoDiferencia = $experienciaEmpresa[0]['montoTotal'] - $this->criterioEvaluacion['montoMinimo'];
        
        if($value['aniosExperiencia']< $this->criterioEvaluacion['antiguedadEmpresa']){
            $estadoAntiguedad = "No";
            $puntajeAntiguedad = 0;
        }else{ 
            $estadoAntiguedad = "Si";
            $puntajeAntiguedad = $this->criterioEvaluacion['puntajeAntiguedad'];
        }
        
        if( $experienciaEmpresa[0]['experienciaGeneralEmpresa'] < $this->criterioEvaluacion['experienciaGeneralAnos']){
            $estadoExperienciaGeneral = "No";
            $puntajeExperienciaGeneral= 0;
        }else{ 
            $estadoExperienciaGeneral = "Si";
            $puntajeExperienciaGeneral= $this->criterioEvaluacion['puntajeExperienciaGeneral'];
        }
        if( $experienciaEspecifica[0]['experienciaEspecificaEmpresa'] < $this->criterioEvaluacion['experienciaEspecificaAnos']){
            $estadoExperienciaEspecifica = "No";
            $puntajeExperienciaEspecifica= 0;
        }else{ 
            $estadoExperienciaEspecifica  = "Si";
            $puntajeExperienciaEspecifica= $this->criterioEvaluacion['puntajeExperienciaGeneral'];
        }
        if( $experienciaEmpresa[0]['montoTotal'] < $this->criterioEvaluacion['montoMinimo']){
            $estadoMontoFacturado = "No";
            $puntajeMontoFacturado = 0;
        }else{ 
            $estadoMontoFacturado = "Si";
            $puntajeMontoFacturado = $this->criterioEvaluacion['puntajeMonto'];
        }
        
        /* ======== TIPO ORGANIZACION =============*/
        if($value['tipoOrganizacion']=='sac')
            $tipoOrganizacion = 'Sociedad Anonima Cerrada';
        if($value['tipoOrganizacion']=='srl')
            $tipoOrganizacion = 'Sociedad de Responsabilidad Limitada';
        if($value['tipoOrganizacion']=='ong')
            $tipoOrganizacion = 'Organizacion no Gubernamental';
        if($value['tipoOrganizacion']=='ie')
            $tipoOrganizacion = 'Institución del Estado';
        /* ======== FIN TIPO ORGANIZACION =============*/
        ?>
       <!-- <table width="750px" border="1" style="border: 5px;border-width: 10px; border-color: #000000"><tr><td>-->
        <table width="740px" border="0" style="font-size: 13px;font-weight: bold;background-color: #B0E0E6; color: #000000">
                <tr>
                    <th style="font-size: 13px;text-align: left;">Empresa:</th>
                    <th colspan="3" style="font-size: 13px;text-align: left;font-weight: normal;"><?php echo $value['nombreEmpresa'];?></th>
                </tr>  
                <tr>
                    <th style="font-size: 13px;text-align: left;font-weight: bold;background-color: #B0E0E6; color: #000000">Tipo de Empresa:</th>
                    <th style="font-size: 13px;text-align: left;font-weight: normal;"><?php echo $tipoOrganizacion;?></th>
                    <th style="font-size: 13px;text-align: left;font-weight: bold;background-color: #B0E0E6; color: #000000">Nacionalidad:</th>
                    <th style="font-size: 13px;text-align: left;font-weight: normal;"><?php echo $value['pais'];?></th>
                </tr>  
        </table>
        <!--</td></tr></table>
        <table width="750px" border="1" style="border: 5px;border-width: 10px; border-color: #000000"><tr><td>-->
        <table width="740px" border="0">
            
            <tr style="background-color: #B0E0E6; color: #000000">
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Criterio</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Cumplimiento</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Diferencia</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Solicitado</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Presentado</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Calificación Max.</td>
            </tr>
            <tr style="background-color: #E0FFFF;" >
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Antiguedad de la Firma</td>
                <td style="text-align: center;"><?php echo $estadoAntiguedad;?></td>
                <td><?php echo $aniosExperienciaDiferencia;?>  Años</td>
                <td><?php echo $this->criterioEvaluacion['antiguedadEmpresa'];?> Años</td>
                <td><?php echo $value['aniosExperiencia'];?> Años</td>
                <td style="text-align:right;padding-right: 10px;"><?php echo $puntajeAntiguedad;?></td>
            </tr>
            <tr>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Experiencia General</td>
                <td style="text-align: center;"> <?php echo $estadoExperienciaGeneral;?></td>
                <td>
                    <?php echo $aniosExperienciaGeneralDiferencia;?> Años,
                    <?php echo $mesesExperienciaGeneralDiferencia;?> Meses
                </td>
                <td>
                    <?php echo $this->criterioEvaluacion['experienciaGeneralAnos'];?> Años,
                    <?php echo $this->criterioEvaluacion['experienciaGeneralMeses'];?> Meses
                </td>
                <td>
                    <?php echo $experienciaEmpresa[0]['experienciaGeneralEmpresa'];?> Años,
                    <?php echo $meses;?> Meses
                </td>
                <td style="text-align:right;padding-right: 10px;"><?php echo $puntajeExperienciaGeneral;?></td>
            </tr>
            <tr style="background-color: #E0FFFF;" >
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Experiencia Específica</td>
                <td style="text-align: center;"><?php echo $estadoExperienciaEspecifica;?></td>
                <td>
                    <?php echo $aniosExperienciaEspecificaDiferencia;?> Años,
                    <?php echo $mesesExperienciaEspecificaDiferencia;?> Meses
                </td>
                <td>
                    <?php echo $this->criterioEvaluacion['experienciaEspecificaAnos'];?> Años,
                    <?php echo $this->criterioEvaluacion['experienciaEspecificaMeses'];?> Meses
                </td>
                <td>
                    <?php echo $experienciaEspecifica[0]['experienciaEspecificaEmpresa'];?> Años,
                    <?php echo $mesesEspecifica;?> Meses
                </td>
                <td style="text-align:right;padding-right: 10px;"><?php echo $puntajeExperienciaEspecifica;?></td>
            </tr>
            <tr>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Monto Facturado</td>
                <td style="text-align: center;"><?php echo $estadoMontoFacturado;?></td>
                <td>S/. <?php echo number_format($montoFacturadoDiferencia, 2) ;?></td>
                <td>S/. <?php echo number_format($this->criterioEvaluacion['montoMinimo'],2);?></td>
                <td>S/. <?php echo number_format($experienciaEmpresa[0]['montoTotal'],2);?></td>
               <td style="text-align:right;padding-right: 10px;"><?php echo $puntajeMontoFacturado;?></td>
            </tr>
            <tr style="background-color: #B0E0E6; color: #000000;font-weight: bold;font-size: 13px;">
                <td colspan="5" style="background-color: #B0E0E6; color: #000000;text-align: right;">TOTAL:</td>
                <td style="text-align:right;padding-right: 10px;">
                    <?php echo $puntajeAntiguedad +
                               $puntajeExperienciaGeneral +
                               $puntajeExperienciaEspecifica +
                                $puntajeMontoFacturado?></td>
            </tr>
            <tr><td colspan="6"><h7><span style="padding-left: 255px;">Evaluación del Personal de la Empresa</span></h7></tr>
        </table>
        
        <!--================================================================================ -->
        <!--========================= CARGOS DE LA EMPRESA =========== ================ -->
        <?php
        foreach($this->listarCargos as $cargo):
            $modelCriterioEvaluacion = new App_Model_CriterioEvaluacion();
            $datosCargoPresentado = $modelCriterioEvaluacion->datosCargoPresentado($idConvocatoria,$cargo['cargo'],$value['idEmpresa']);
            
            
           if($datosCargoPresentado['expanos']==""){ 
                 $datosCargoPresentadoAnios = '0';
            }else{ 
                 $datosCargoPresentadoAnios =  $datosCargoPresentado['expanos'];
                 
            }
            
            if($datosCargoPresentado['expmeses']!=""){
                $datosCargoPresentadoMeses = $datosCargoPresentado['expmeses'];
             }else{
                 $datosCargoPresentadoMeses = '0';
             }  
            
           $restoAnos =  $datosCargoPresentadoAnios - $cargo['experienciaGeneralAnos'];
           $restoMeses = $datosCargoPresentadoMeses - $cargo['experienciaGeneralMeses']; 
           
           if( $cargo['experienciaGeneralAnos'] > $datosCargoPresentadoAnios){
               $cumpleAnios = "No";
           }else{ $cumpleAnios = "Si";}
           
           $foco = 0;
           if($datosCargoPresentado['profesion'] == ""){
               $profesionCargoPresentado = "---------------";
               $cumpleProfesion = "No";
               }else{
                   $profesionCargoPresentado = $datosCargoPresentado['profesion']; 
                    foreach($this->listarProfesion as $profesion):
                        if($profesionCargoPresentado == $profesion['profesion'])
                            $foco = 1;
                    endforeach;
                    if($foco == 1){$cumpleProfesion = "Si"; $foco = 0;}else{$cumpleProfesion = "No";}
                   } 
            
           if($datosCargoPresentado['especialidad'] == ""){ 
               $especialidadCargoPresentado = "---------------";
               $cumpleEspecialidad = "No";
               }else{
                   $especialidadCargoPresentado = $datosCargoPresentado['especialidad']; 
                   foreach($this->listarEspecialidad as $especialidad):
                        if($especialidadCargoPresentado == $especialidad['especialidad'])
                           $foco = 1;
                    endforeach;
                    if($foco == 1){$cumpleEspecialidad = "Si"; $foco = 0;}else{$cumpleEspecialidad = "No";}
                   } 
            
           if($datosCargoPresentado['subespecialidad'] == ""){
               $subespecialidadCargoPresentado = "---------------";
               $cumpleSubEspecialidad = "No";
               }else{
                   $subespecialidadCargoPresentado = $datosCargoPresentado['subespecialidad']; 
                   foreach($this->listarSubEspecialidad as $subEspecialidad):
                         if($subespecialidadCargoPresentado == $subEspecialidad['subEspecialidad'])
                            $foco = 1;
                    endforeach;
                    if($foco == 1){$cumpleSubEspecialidad = "Si"; $foco = 0;}else{$cumpleSubEspecialidad = "No";}
                    
                   } 
           
        ?>
        <table width="740px" border="0">
            <tr style="background-color: #B0E0E6; color: #000000">
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Cargo:</td>
                <td style="font-size: 13px;text-align: left;" colspan="4"><?php echo $cargo['cargo']?></td>
            </tr>
            <tr style="background-color: #B0E0E6; color: #000000">
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Criterio</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Cumplimiento</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Diferencia</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Solicitado</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Presentado</td>
            </tr>
            <tr>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Profesión (es)</td>
                <td style="text-align: center;"><?php echo $cumpleProfesion;?></td>
                <td>-----------------</td>
                <td><?php  if(count($this->listarProfesion)>0){
                                foreach($this->listarProfesion as $profesion):
                                    echo $profesion['profesion']."<br>";
                                endforeach;
                          }else{
                              echo "NO SOLICITA";
                          }
                          ?> 
                </td>
                <td><?php echo $profesionCargoPresentado;?> </td>
            </tr>
            <tr style="background-color: #E0FFFF;" >
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Especialidad</td>
                <td style="text-align: center;"><?php echo $cumpleEspecialidad;?></td>
                <td>-----------------</td>
                <td><?php if(count($this->listarEspecialidad)>0){
                            foreach($this->listarEspecialidad as $especialidad):
                                echo $especialidad['especialidad']."<br>";
                            endforeach;
                         }else{
                              echo "NO SOLICITA";
                          }
                    ?> 
                </td>
                <td><?php echo $especialidadCargoPresentado;?></td>
            </tr>
            <tr>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">SubEspecialidad</td>
                <td style="text-align: center;"><?php echo $cumpleSubEspecialidad;?></td>
                <td>-----------------</td>
                <td><?php if(count($this->listarSubEspecialidad)>0){
                            foreach($this->listarSubEspecialidad as $subEspecialidad):
                                echo $subEspecialidad['subEspecialidad'];
                            endforeach;
                         }else{
                              echo "NO SOLICITA";
                          }
                    ?> 
                </td>
                <td><?php echo $subespecialidadCargoPresentado;?></td>
            </tr>
            <tr style="background-color: #E0FFFF;">
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Experiencia General</td>
                <td style="text-align: center;"><?php echo $cumpleAnios;?> </td>
                <td><?php echo $restoAnos; ?> Años
                <?php echo $restoMeses; ?> Meses</td>
                <td><?php echo $cargo['experienciaGeneralAnos'];?> Años
                    <?php echo $cargo['experienciaGeneralMeses'];?> Meses
                </td>
                <td><?php echo $datosCargoPresentadoAnios;?> Años
                    <?php echo $datosCargoPresentadoMeses;?> Meses
                </td>
            </tr>
            <tr><td colspan="5">&nbsp;</tr>
        </table>
        <?php  endforeach;?>
        <!--=========================== FIN DE CARGOS DE EMPRESA =========================== -->
        <!--================================================================================ -->
        <!-- </td></tr></table>-->
        <?php endforeach; ?>
        _____________________________________________________________________________________________
        <h5>Resultados Generales: Se presentarón  <?php echo count($this->empresas);?> empresas.</h5>
    </body>
</html>


