<!DOCTYPE html>
<html>
    <head>
        <title> SOFTEIN - REPORT</title>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
        <style>
            td{
                padding-top: 5px; padding-bottom: 5px;
            }
            #personal td{
                padding-top: 10px; padding-bottom: 10px;
                padding-left: 10px;padding-right: 10px;
                text-align: left;
            }
        </style>        
    
    </head>
    <body>
        <h3>Datos Empresa </h3>
        <table width="800px">
            <tr>
                <td width="150px">Empresa : </td>
                <td><?php echo $this->empresa['nombreEmpresa'] ?> </td>
            </tr>            
            <tr>
                <td>RUC : </td>
                <td><?php echo $this->empresa['numeroDocumento'] ?> </td>
            </tr>
            <tr>
                <td>Email : </td>
                <td><?php echo $this->empresa['email'] ?> </td>
            </tr>
            <tr>
                <td>Telefono : </td>
                <td><?php echo $this->empresa['telefono'] ?> </td>
            </tr>
            
            <tr>
                <td>Convocatoria : </td>
                <td><?php echo $this->empresa['proceso'] ?> </td>
            </tr>
            
        </table>
        <br/>
        <h4>Personal participante en la convocatoria</h4>
        
        <table id ="personal"width="600px" style="border-collapse: collapse;" border="1">
            <thead>
                <tr>
            <th> Nombre</th>
            <th> Cargo</th>
            <th> Email</th>
            <th> Nivel Académico</th>
            <th> Teléfono</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->personal as $value) { ?>
            <tr>                
                <td><?php echo $value['nombre'] . " " . $value['apellido'] ?> </td>                
                <td><?php echo $value['cargo'] ?> </td>                
                <td><?php echo $value['email'] ?> </td>                
                <td><?php echo $value['nivelacademico'] ?> </td>                
                <td><?php echo $value['telefono'] ?> </td>
            </tr>
            <?php } ?>
            </tbody>
        </table>
        
    </body>
</html>


