<!DOCTYPE html>
<html>
    <head>
        <title> SOFTEIN - REPORT</title>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    
    </head>
    <body>
        <h6> --- Fecha de Convocatoria: dd/mm/aaaa   fecha de cierre: dd/mm/aaaa --- </h6>
        _____________________________________________________________________________________________
        <br>
        <br>
        <h3></h3>
        <?php foreach ($this->empresas as $value) :?>
        <table width="750px" border="2">
                <tr>
                    <th style="font-size: 13px;text-align: left;font-weight: bold;">Empresa:</th>
                    <th colspan="3" style="font-size: 13px;text-align: left;font-weight: normal;"><?php echo $value['nombreEmpresa'];?></th>
                </tr>  
                <tr>
                    <th style="font-size: 13px;text-align: left;font-weight: bold;">Tipo de Empresa:</th>
                    <th style="font-size: 13px;text-align: left;font-weight: normal;">Comercial:</th>
                    <th style="font-size: 13px;text-align: left;font-weight: bold;">Nacionalidad:</th>
                    <th style="font-size: 13px;text-align: left;font-weight: normal;"><?php echo $value['pais'];?></th>
                </tr>  
        </table>
        <br>
        <table width="750px" border="2">
            
            <tr>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Criterio</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Cumplimiento</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Diferencia</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Solicitado</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Presentado</td>
                <td style="font-size: 13px;text-align: left;font-weight: bold;">Calificación Max.</td>
            </tr>
            <tr><td>Antiguedad de la Firma</td>
                <td>Cumplimiento</td>
                <td>Diferencia</td>
                <td><?php echo $this->criterioEvaluacion['antiguedadEmpresa'];?></td>
                <td>Presentado</td>
                <td><?php echo $this->criterioEvaluacion['puntajeAntiguedad'];?></td>
            </tr>
            <tr><td>Experiencia General</td>
                <td>Cumplimiento</td>
                <td>Diferencia</td>
                <td><?php echo $this->criterioEvaluacion['experienciaGeneralAnos'];?></td>
                <td>Presentado</td>
                <td><?php echo $this->criterioEvaluacion['puntajeExperienciaGeneral'];?></td>
            </tr>
            <tr><td>Experiencia Específica</td>
                <td>Cumplimiento</td>
                <td>Diferencia</td>
                <td><?php echo $this->criterioEvaluacion['experienciaEspecificaAnos'];?></td>
                <td>Presentado</td>
                <td><?php echo $this->criterioEvaluacion['puntajeExperienciaEspecifica'];?></td>
            </tr>
            <tr><td>Monto Facturado</td>
                <td>Cumplimiento</td>
                <td>Diferencia</td>
                <td><?php echo $this->criterioEvaluacion['montoMinimo'];?></td>
                <td>Presentado</td>
               <td><?php echo $this->criterioEvaluacion['puntajeMonto']?></td>
            </tr>
            <tr>
                <td colspan="5" style="text-align: right;">TOTAL:</td>
                <td><?php echo $this->criterioEvaluacion['puntajeAntiguedad']+
                                $this->criterioEvaluacion['puntajeExperienciaGeneral']+
                                $this->criterioEvaluacion['puntajeExperienciaEspecifica']+
                                $this->criterioEvaluacion['puntajeMonto']?></td>
            </tr>
        </table>
        <br>
        <?php endforeach; ?>
        
        
        
        
        
        
    </body>
</html>


