
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
        <div class="box-header well" data-original-title="">
<h2><i class="icon-list"></i> Actualización Convocatoria - Plazo </h2>
						
	   </div>
       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 30px;" aria-label="Status: activate to sort column ascending">
                                            Código
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Convocatoria
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Fecha Inicio
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Fecha Limite
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Hora Limite
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Acción
                                        </th>
                                        
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->lista as $convocatoria):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $convocatoria['codigo']?></td>
                                        <td class="center "><?php echo $convocatoria['proceso']?></td>
                                        <td class="center "><?php echo $convocatoria['fecha']?></td>
                                        <td class="center "><?php echo $convocatoria['limite']?></td>
                                        <td class="center "><?php echo $convocatoria['hora_lim']?></td>
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/convocatoria/modificar-plazo/id/<?php echo $convocatoria["ID"]; ?>">
                                                <i class="icon-upload"></i>  
                                                Actualizar
                                            </a>
                                            <a class="btn btn-success" href="/admin/procesos/modificar-seleccion/id/<?php echo $convocatoria["ID"]; ?>">
                                                <i class="icon-list icon-white"></i>  
                                                Criterios de Selección
                                            </a>
                                            <a class="btn btn-danger" href="/admin/procesos/evaluar-convocatoria-plazo/id/<?php echo $convocatoria["ID"]; ?>">
                                                <i class="icon-adjust"></i>  
                                                Evaluar Convocatorias
                                            </a>
                                        </td>
                                        
                                        
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>


