<!-- Start: login-holder -->
<div id="login-holder">

	<!-- start logo -->
	<div id="logo-login">
            <span style="font-size: 30px; color: #ffffff;font-weight: bold; text-align: center;letter-spacing: 2px;"> 
                Sistema de Gestión de Convocatorias para Empresas (SIGECE)
            </span>
	</div>
       
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="loginbox">
	
	<!--  start login-inner -->
	<div id="login-inner">
            <form  method="post" name="login" id="login">
		<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<th>E-mail : </th>
                        <td><input type="text"  id="email"  name="email"  class="login-inp"  /></td>
		</tr>
		<tr>
			<th>Password:</th>
                        <td><input type="password"  id="clave"  name="clave"  class="login-inp"/></td>
		</tr>
		<tr>
			<th></th>
			<td valign="top">
                        </td>
		</tr>
		<tr>
			<th></th>
                        <td >
                            <input type="submit" class="button medium blue"  value=" Ingresar " />
                            <input type="button" class="button medium blue"   value=" Regístrese (para accesos por primera vez)"  
                                   onclick="window.location='/admin/registro/'">
                        </td>
		</tr>
		</table>
		</form>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	<a href="" class="forgot-pwd">¿Recuperar su password?</a> </div>
 <!--  end loginbox -->
 
	<!--  start forgotbox ................................................................................... -->
	<div id="forgotbox">
            <form  method="post" name="login" id="login" action="/admin/auth/clave">
		<div id="forgotbox-text">Le enviaremos un email para restablecer su password.</div>
		<!--  start forgot-inner -->
		<div id="forgot-inner">
		<table border="0" cellpadding="0" cellspacing="0">
		<tr>
			<th>Ingrese E-mail</th>
                        <td><input type="text" value=""  name="email" id="email" class="login-inp" /></td>
		</tr>
		<tr>
			<th> </th>
                        <td><input type="submit" class="button medium blue"  value="Enviar" /></td>
		</tr>
		</table>
		</div>
		<!--  end forgot-inner -->
		<div class="clear"></div>
		<a href="" class="back-login">Login</a>	
              </form>
        </div>
	<!--  end forgotbox -->

</div>
<!-- End: login-holder -->
