<form method="post" name="altaAlumno" action="index.html">

		<center>
		<p>* datos obligatorios</p>
		<table>
		<tr>
			<td><p align="right">*Nombre(s): </p></td>
			<td><input type="text" id="nombre" name="nombre" size="30" maxlength="20"  class="jsrequired"><br></td>
		</tr>
		<tr>
			<td><p align="right">*Apellido Paterno: </p></td>
			<td><input type="text" id="apePaterno" name="apePaterno" size="30" maxlength="20"  class="jsrequired"></td>
		</tr>
		<tr>
			<td><p align="right">*Apellido Materno: </p></td>
			<td><input type="text" id="apeMaterno" name="apeMaterno" size="30" maxlength="20"  class="jsrequired"></td>
		</tr>
		<tr>
			<td><p align="right"><a href="javascript:ventanaSecundaria('curp/index.html')">Obtener </a>CURP: </p></td>
			<td><input type="text" id="curp" name="curp" size="30" maxlength="18"  class="jsvalidate_curp_mx"></td>
		</tr>

		<tr>
			<td  valing="top"><p align="right">*Fecha de Nacimiento: <br>AAAA-MM-DD</p></td>
			<td><input type="text" id="anio" name="fecNac" size="30" maxlength="10"  class="jsvalidate_fecha jsrequired"></td>
		</tr>
		<tr>
<td><p align="right">N&uacute;mero de Seguro Social: <br>00-00-00-000-0</p></td>
			<td><input type="text" id="numSeguro" name="numSeguro" size="30"  maxlength="14" class="jsvalidate_ssn_mx"> </td>
		</tr>
		<tr>
			<td><p align="right">C&oacute;digo Postal:</p></td>
			<td><input type="text" id="codPostal" name="codPostal" size="30"  class="jsvalidate_digits"></td>
		</tr>

		<tr>
<td><p align="right">Tel&eacute;fono Fijo (01):<br>(10 d&Iacute;gitos)</p></td>
			<td><input type="text" id="telFijo" name="telFijo" size="30" maxlength="10"  class="jsvalidate_telefono"> </td>
		</tr>
		<tr>
<td><p align="right">Tel&eacute;fono M&oacute;vil:<br>(10 d&iacute;gitos)</p></td>
		<td><input type="text" id="movil" name="movil" size="30" maxlength="10"  class="jsvalidate_telefono"></td>
		</tr>
		<tr>
			<td><p align="right">Correo Electr&oacute;nico:</p></td>
			<td><input type="text" id="eMail" name="eMail" size="30"  class="jsvalidate_email"></td>
		</tr>
		<tr>
			<td><p align="right">Bachillerato de Procedencia:</p></td>
			<td><input type="text" id="bach" name="bach" size="30"  ></td>
		</tr>

		<tr>
<td><p align="right">*Matr&iacute;cula:<br>(10 d&iacute;gitos)</p></td>
			<td><input type="text" id="matricula" name="matricula" size="30"  maxlength="10" class="jsvalidate_telefono jsrequired"> </td>
		</tr>

		</table>

		<br>

		<p><input type=image src="Boton-Continuar1.png" name="sub"></p>

		</form>
