<script type="text/javascript">
$(document).ready(function() {
    $("#fichaForm").validate();
});
$(document).submit(function() {
    var fechaConstitucion = $("input#fechaConstitucion").val();
    var aniosExperiencia = $("input#aniosExperiencia").val();
    var fecha = new Date();
    var ano = fecha.getFullYear();
    var partes = fechaConstitucion.split('-');
    var resto =  parseInt(ano) -parseInt(partes[2]);

/* alert(fechaConstitucion);
    alert(aniosExperiencia);
    alert(ano);
    alert(partes[2]);
    alert(resto);
*/
    
    if( aniosExperiencia > resto ){
        alert("La cantidad de años de experiencia de la empresa NO \n\
            puede ser mayor a la que referencia su fecha de constitución");
        return false;
    }else{
        return true;
    }

});
</script>

<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Home</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="#">Datos de la Empresa</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">
   
        
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Datos Principales</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <form  id="fichaForm" name="fichaForm" action="" method="post" enctype="multipart/form-data" >
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
               
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span10">
                                    <div class="clear"></div>
                                    <label for="Pais Empresa" class="span3 no-margin">Pais de la Empresa :</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->paisEmpresa;?>
                                        
                                    </div>
                                    <div class="clear"></div>
                                    <label for="tipoDocumento" class="span3 no-margin">Tipo Documento :</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->tipoDocumento;?>
                                        
                                    </div>

                                    <div class="clear"></div>
                                    <label for="nroDocumento" class="span3 no-margin">Nro. Documento:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->numeroDocumento;?>
                                    </div>
                                    <div class="clear"></div>
                                    <label for="nombreEmpresa" class="span3 no-margin">Empresa:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->nombreEmpresa;?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="representanteLegal" class="span3 no-margin">Representante Legal:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->representanteLegal;?>
                                    </div>
                                    <div class="clear"></div>
                                    <label for="telefono" class="span3 no-margin">Número telefónico:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->telefono;?>
                                    </div>    
                                    <div class="clear"></div>
                                    <label for="email" class="span3 no-margin">E-mail:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->email;?>
                                    </div>
                                    <div class="clear"></div>
                                    <label for="clave" class="span3 no-margin">Clave:</label>
                                    <div class="span8 no-margin">
                                        <?php //echo $this->form->clave;?>
                                        <input  type="password" id="clavesita" name="clavesita" class="required" value="........"/>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="clave" class="span3 no-margin"></label>
                                    <div class="span8 no-margin">
                                        (SOLO escriba aquí si desea cambiar su clave).
                                    </div>
                                    
                                   
                                </div>
                                <div class="clear"></div>

                            </div>
                            
                    </div>
                </div>
            </div>          
            </div>            
        </div>
        
        
        
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Datos Complementarios</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span10">
                                    <div class="clear"></div>
                                    <label for="cantEmpleados" class="span3 no-margin">Cantidad de Empleados:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->cantEmpleados;?>
                                        
                                    </div>

                                    <div class="clear"></div>
                                    <label for="fechaConstitucion" class="span3 no-margin">Fecha de Constitución:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->fechaConstitucion;?> (DD-MM-AAAA)
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="aniosExperiencia" class="span3 no-margin">Años de Experiencia:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->aniosExperiencia;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="nroFicha" class="span3 no-margin">Número de Ficha Registral:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->nroFicha;?>
                                    </div>
                                    <!--
                                    <div class="clear"></div>
                                    <label for="pdfRuc" class="span3 no-margin">PDF:</label>
                                    <div class="span8 no-margin">
                                        <?php //echo $this->form->pdfRuc;?>
                                    </div>
                                    -->
                                    
                                    <label for="fax" class="span3 no-margin">Fax:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->fax;?>
                                    </div>
                                    
                                    <label for="url" class="span3 no-margin">Web:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->url;?>
                                        
                                    </div>
                                    
                                    <label for="opcion" class="span3 no-margin">Tipo de Organización:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->tipoOrganizacion;?>
                                    </div>
                                    
                                     <div class="clear"></div>
                                    <label for="otros" class="span3 no-margin">Otros:</label>
                                    <div class="span8 no-margin">
                                        <?php echo $this->form->otros;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                   
                                </div>
                                <div class="clear"></div>

                            </div>
                            <div class="form-actions">
                                <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                            </div> 
                    </div>
                </div>
            </div>          
            </div>            
        </div>
           </form>
       
        <!--
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Convocatorias </h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
        <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">                        <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Nombre
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 150px;" aria-label="Date registered: activate to sort column ascending">
                                            Apellido
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Cargo
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Fecha Reg.
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 90px;" aria-label="Status: activate to sort column ascending">
                                            Estado
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 150px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->listaContacto as $contacto):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $contacto['nombre']?></td>
                                        <td class="center "><?php echo $contacto['apellido']?></td>
                                        <td class="center "><?php echo $contacto['cargo']?></td>
                                        <td class="center "><?php echo $contacto['fechaRegistro']?></td>
                                        <td class="center ">
                                            <?php if ($contacto['estado'] == 1) : ?>
                                                <span class="label label-success">Activo</span>
                                            <?php endif; ?>
                                            <?php if ($contacto['estado'] == 0) : ?>
                                                <span class="label label-important">Eliminado</span>
                                            <?php endif; ?>
                                            
                                        </td>
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/contacto/editar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-edit icon-white"></i>  
                                                Edit                                            
                                            </a>
                                            <a class="btn btn-danger" href="/admin/contacto/eliminar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-trash icon-white"></i> 
                                                Delete
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
            </div>         
        </div>
        
        -->
        
        
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Personas de Contacto</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable " 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Nombre
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 150px;" aria-label="Date registered: activate to sort column ascending">
                                            Apellido
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Cargo
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Fecha Reg.
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 70px;" aria-label="Status: activate to sort column ascending">
                                            Estado
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 170px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->listaContacto as $contacto):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $contacto['nombre']?></td>
                                        <td class="center "><?php echo $contacto['apellido']?></td>
                                        <td class="center "><?php echo $contacto['cargo']?></td>
                                        <td class="center "><?php echo $contacto['fechaRegistro']?></td>
                                        <td class="center ">
                                            <?php if ($contacto['estado'] == 1) : ?>
                                                <span class="label label-success">Activo</span>
                                            <?php endif; ?>
                                            <?php if ($contacto['estado'] == 0) : ?>
                                                <span class="label label-important">Eliminado</span>
                                            <?php endif; ?>
                                            
                                        </td>
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/contacto/editar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-edit icon-white"></i>  
                                                Editar                                           
                                            </a>
                                            <a class="btn btn-danger" href="/admin/contacto/eliminar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-trash icon-white"></i> 
                                                Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
            </div>         
        </div>
    </div>
 

</div>
<script>
$(document).ready(function(){    
    $("#fechaConstitucion").datepicker();
    $( "#fechaConstitucion" ).datepicker( "option", "dateFormat", "dd-mm-yy" );
    $("#fechaConstitucion").val("<?=$this->fechaConstitucion?>");
});
</script>
