<div class="well sidebar-nav span10">
<ul class="nav nav-list">    
    <li class="nav-header">ACCESOS RAPIDOS A:</li>
    <?php if ($this->authData->tipoUsuario == 1) { ?>
    <li><a href="/admin/empresa/mis-datos"><span style="font-weight: bold;"> 1 &nbsp</span> Datos de la Empresa</a></li>
    <li><a href="/admin/experiencia/"><span style="font-weight: bold;"> 2 &nbsp</span>Experiencia de la Empresa</a></li>
    <li><a href="/admin/contacto/"><span style="font-weight: bold;"> 3 &nbsp</span>Personas de Contacto</a></li>
    <li><a href="/admin/convocatoria/"><span style="font-weight: bold;"> 4 &nbsp</span>Convocatorias</a></li>
    <li><a href="/admin/personal/"><span style="font-weight: bold;"> 5 &nbsp</span>Personal Empresa</a></li>
    <li><a href="/admin/consorcio/"><span style="font-weight: bold;"> 6 &nbsp</span>Empresas Consorcio</a></li>
   <!-- <li><a href="/admin/convocatoria/">Personal de la Empresa</a></li>-->
   <?php } elseif($this->authData->tipoUsuario == 2) {?>
   <li><a href="/admin/reportes/"><span style="font-weight: bold;"> 1 &nbsp</span>Reporte Convocatoria</a></li>
   <?php } ?>

</ul>
</div>

