<div class="well sidebar-nav span10">
<ul class="nav nav-list">    
    <li class="nav-header">Menú de opciones:</li>
    <?php if ($this->authData->tipoUsuario == 1) { ?>
    <li><a href="/admin/empresa/mis-datos"><span style="font-weight: bold;"> 1 &nbsp</span> Datos de la Empresa</a></li>
    <li><a href="/admin/experiencia/"><span style="font-weight: bold;"> 2 &nbsp</span>Experiencia de la Empresa</a></li>
    <li><a href="/admin/contacto/"><span style="font-weight: bold;"> 3 &nbsp</span>Personas de Contacto</a></li>
    <li><a href="/admin/personal/"><span style="font-weight: bold;"> 4 &nbsp</span>Personal de la Empresa</a></li>
    
    <li><a href="/admin/consorcio/"><span style="font-weight: bold;"> 5 &nbsp</span>Empresas Consorcio</a></li>
    <li><a href="/admin/convocatoria/"><span style="font-weight: bold;"> 6 &nbsp</span>Convocatorias</a></li>
    
   <!-- <li><a href="/admin/convocatoria/">Personal de la Empresa</a></li>-->
   <?php } elseif($this->authData->tipoUsuario == 2) {?>
   <li><a href="/admin/reportes/"><span style="font-weight: bold;"> 1 &nbsp</span>Reporte Convocatoria</a></li>
   <li><a href="/admin/reportes/convocatoria-activa"><span style="font-weight: bold;"> 2 &nbsp</span>Convocatorias Activas</a></li>
   <li><a href="/admin/reportes/convocatoria-inactiva"><span style="font-weight: bold;"> 3 &nbsp</span>Convocatorias Inactivas</a></li>
   <li><a href="/admin/reportes/modificar-plazo"><span style="font-weight: bold;"> 4 &nbsp</span>Actualización de Plazo</a></li>
   <li><a href="/admin/procesos/criterios-seleccion"><span style="font-weight: bold;"> 5 &nbsp</span>Criterios de Selección</a></li>
   <li><a href="/admin/reportes/evaluar"><span style="font-weight: bold;"> 6 &nbsp</span>Evaluar postulaciones de empresas</a></li>
   
   <?php } ?>

</ul>
</div>

