<div class="well sidebar-nav span10">
<ul class="nav nav-list">    
    <li class="nav-header">ACCESOS RAPIDOS A:</li>
    <li><a href="/admin/empresa/mis-datos">Mis Datos</a></li>
    <li><a href="/admin/experiencia/">Experiencia de la Empresa</a></li>
    <li><a href="/admin/contacto/">Personas de Contado</a></li>
   <!-- <li><a href="/admin/convocatoria/">Personal de la Empresa</a></li>-->
   
    

</ul>
</div>

