<?php echo $this->doctype()?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Administrador</title>
        
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/styles/admin.css"/>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/main.css"/>
        <link rel="stylesheet" href="<?php echo MEDIA_URL?>/css/screenLogin.css"/>
        
        <link href="<?php echo SITE_URL ?>static/css/bootstrap-responsive.css" rel="stylesheet">
        
        <script src="<?php echo MEDIA_URL?>/js/jquery/jquery-1.4.1.min.js" type="text/javascript"></script>
        <!-- Custom jquery scripts -->
        <script src="<?php echo MEDIA_URL?>/js/jquery/custom_jquery.js" type="text/javascript"></script>

        <!-- MUST BE THE LAST SCRIPT IN <HEAD></HEAD></HEAD> png fix -->
        <script src="<?php echo MEDIA_URL?>/js/jquery/jquery.pngFix.pack.js" type="text/javascript"></script>
        
        <?=$this->headLink()?>
        <?=$this->headScript()?>
        <?=$this->headStyle()?>
    </head>
    
    <body id="login-bg"> 
        <?php echo $this->render('_messages.phtml');?>
        <?php echo $this->layout()->content?>
    </body>
</html>