<script type="text/javascript">
$(document).ready(function() {
	$("#experiencia").validate();
});

$(document).submit(function() {

    var a =  $("#fechaInicio").datepicker("getDate");
    var b = $("#fechaFin").datepicker("getDate");
    
    if( b < a){
        alert("Fecha Final es menor que Fecha Inicial");
        $("#fechaFin").focus();
        return false;
    }else{    
       return true;
    }
});
</script>

<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/consorcio/editar/id/<?php echo $this->empresa;?>">Datos del Consorcio</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/consorcio/experiencia/empresa/<?php echo $this->empresa;?>">Experiencia de la Empresa</a> <span class="divider">/</span>
            </li>
            <li>
                    Nueva Experiencia            
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">
    
    <div class="box span12">
        <form name="experiencia" id="experiencia" action="" method="post" enctype="multipart/form-data" >
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Experiencia de la Empresa</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span10">
                                    
                                    <div class="clear"></div>
                                    <label for="servicioPais" class="span3 no-margin">Pais:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->servicioPais;?>
                       
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="servicioEmpresa" class="span3 no-margin">Empresa destinataria del servicio o venta:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->servicioNombre;?>
                                       
                                    </div>

                                    <div class="clear"></div>
                                    <label for="servicioRuc" class="span3 no-margin">RUC:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->servicioRuc;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaInicio" class="span3 no-margin">Fecha de Inicio:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->fechaInicio;?> (YYYY-MM-DD)
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaFin" class="span3 no-margin">Fecha de Fin:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->fechaFin;?> (YYYY-MM-DD)
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="observacion" class="span3 no-margin">Observaciones :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->observacion;?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="descripcion" class="span3 no-margin">Descripción:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->descripcion;?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="enCurso" class="span3 no-margin">En Curso:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->enCurso;?>
                                    </div>
                                    <div class="clear"></div>
                                    <label for="montoTotal" class="span3 no-margin">Monto total S/. :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->montoTotal;?>
                                    </div>
                                    
                                   
                                </div>
                                <div class="clear"></div>

                            </div>
                            
                    </div>
                </div>
            </div>          
            </div>            
        </div>
        
        
        
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Persona de Referencia </h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span8">
                                    <div class="clear"></div>
                                    <label for="referenciaNombre" class="span3 no-margin">Nombre Completo:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->referenciaNombre;?>
                                        
                                    </div>

                                    <div class="clear"></div>
                                    <label for="referenciaEmail" class="span3 no-margin">Email:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->referenciaEmail;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="referenciaCargo" class="span3 no-margin">Cargo:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->referenciaCargo;?>
                                        
                                    </div>

                                    <div class="clear"></div>
                                    <label for="referenciaTelefono" class="span3 no-margin">Telefono:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->referenciaTelefono;?>
                                        
                                    </div>

                                    
                                    <div class="clear"></div>
                                    <?php echo $this->form->csrf; ?>
                                    <?php if ($this->form->csrf->hasErrors()) echo "Intentalo nuevamente";?>
                                </div>
                                <div class="clear"></div>

                            </div>
                            <div class="form-actions">
                                <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                            </div> 
                    </div>
                </div>
            </div>          
            </div>            
        </div>
     </form>
    </div>
    
    <!--/span-->
</div>
<script>
$(document).ready(function(){    
    $("#fechaInicio").datepicker({
        "dateFormat" : "yy-mm-dd",
        onClose: function( selectedDate ) {
            console.log(selectedDate);
            fecha = selectedDate.split("-");
            console.log(fecha);
            f = new Date(fecha[0], parseInt(fecha[1]) - 1, fecha[2]);
            $( "#fechaFin" ).datepicker( "option", "minDate", f);
            $( "#fechaFin" ).val(selectedDate);
        }
    });
    $( "#fechaInicio" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    $( "#fechaInicio" ).val("<?=$this->experiencia["fechaInicio"]?>");
    $("#fechaFin").datepicker();
    $( "#fechaFin" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    $( "#fechaFin" ).val("<?=$this->experiencia["fechaFin"]?>");
});
</script>