<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/consorcio/editar/id/<?php echo $this->empresa;?>">Datos del Consorcio</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/consorcio/experiencia/empresa/<?php echo $this->empresa;?>">Experiencia de la Empresa</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/consorcio/experiencia-crear/empresa/<?php echo $this->empresa?>">Agregar Experiencia</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">

       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable dataTable dataTable" 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 180px;" aria-label="Status: activate to sort column ascending">
                                            Pais
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Empresa
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 100px;" aria-label="Date registered: activate to sort column ascending">
                                            RUC
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 130px;" aria-label="Role: activate to sort column ascending">
                                            Fecha Inicio
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 130px;" aria-label="Role: activate to sort column ascending">
                                            Fecha Fin.
                                        </th>
                                        
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 150px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->listaExperiencia as $experiencia):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $experiencia['pais']?></td>
                                        <td class="center "><?php echo $experiencia['servicioNombre']?></td>
                                        <td class="center "><?php echo $experiencia['servicioRuc']?></td>
                                        <td class="center "><?php echo $experiencia['fechaInicio']?></td>
                                        <td class="center "><?php echo $experiencia['fechaFin']?></td>
                                        
                                        <td class="center ">
                                            <a class="btn btn-info" 
                                               href="/admin/consorcio/experiencia-editar/id/<?php echo $experiencia["idDetalleEmpresa"]; ?>/idEmpresa/<?php echo $this->empresa;?>">
                                                <i class="icon-edit icon-white"></i>  
                                                Editar                                            
                                            </a>
                                            <a class="btn btn-danger" 
                                               href="/admin/consorcio/experiencia-eliminar/id/<?php echo $experiencia["idDetalleEmpresa"]; ?>/idEmpresa/<?php echo $this->empresa;?>"
                                               onclick="return confirm('Seguro que desea eliminar el registro?')">
                                                <i class="icon-trash icon-white"></i> 
                                                Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>