<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Listado Consorcios</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/consorcio/crear">Agregar Consorcio</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 180px;" aria-label="Status: activate to sort column ascending">
                                            Nombre Empresa
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Representante
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 100px;" aria-label="Date registered: activate to sort column ascending">
                                            Teléfono
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 100px;" aria-label="Role: activate to sort column ascending">
                                            Fecha Registro
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 170px;" aria-label="Actions: activate to sort column ascending">
                                            Acciones
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->lista as $experiencia):
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $experiencia['nombreEmpresa']?></td>
                                        <td class="center "><?php echo $experiencia['representanteLegal']?></td>
                                        <td class="center "><?php echo $experiencia['telefono']?></td>
                                        <td class="center "><?php echo $experiencia['fechaRegistro']?></td>
                                        
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/consorcio/editar/id/<?php echo $experiencia["idEmpresa"]; ?>">
                                                <i class="icon-list"></i>  
                                                Detalles Empresa
                                            </a>
                                            
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>