<script type="text/javascript">
$(document).ready(function() {
	$("#experiencia").validate();
});
</script>

<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/experiencia">Personal Empresa</a> <span class="divider">/</span>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">
    
    <div class="box span12">
        <form name="personal" id="personal" action="" method="post" enctype="multipart/form-data" >
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Datos </h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span10">
                                    
                                    <div class="clear"></div>
                                    <label for="nombre" class="span3 no-margin">Nombre :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->nombre;?>
                       
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="apellido" class="span3 no-margin">Apellidos :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->apellido;?>                                       
                                    </div>

                                    <div class="clear"></div>
                                    <label for="cargo" class="span3 no-margin">Cargo :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->cargo;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="numerodocumento" class="span3 no-margin">DNI :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->numerodocumento;?>                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="email" class="span3 no-margin">Email :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->email;?>
                                        
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="telefono" class="span3 no-margin">Teléfono :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->telefono;?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="nivelacademico" class="span3 no-margin">Nivel Académico :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->nivelacademico;?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="tipo" class="span3 no-margin">Tipo :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->tipo;?>
                                    </div>
                                    <div class="clear"></div>
                                    <div class="clear"></div>
                                    <label for="expanos" class="span3 no-margin">Experiencia Años:</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->expanos;?>
                                    </div>
                                    <div class="clear"></div>
                                    <label for="expmeses" class="span3 no-margin">Experiencia en Meses :</label>
                                    <div class="span7 no-margin">
                                        <?php echo $this->form->expmeses;?>
                                        <?php echo $this->form->csrf;?>
                                    </div>
                                    
                                   
                                </div>
                                <div class="clear"></div>
                            <div class="form-actions">
                                <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>
                            </div> 
                            </div>
                            
                    </div>
                </div>
            </div>          
            </div>            
        </div>        

     </form>
    </div>
    
    <!--/span-->
</div>