
<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/experiencia">Experiencia de la Empresa</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="#">Nueva Experiencia</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">
    
    <div class="box span12">
        <form action="" method="post" enctype="multipart/form-data" >
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Datos Principales</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span6">
                                    
                                    <div class="clear"></div>
                                    <label for="servicioPais" class="span5 no-margin">Pais:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->servicioPais->setAttrib('maxlength', '60')->renderViewHelper();?>
                                        <?php if ($this->form->servicioPais->hasErrors()) echo "Ingrese Pais";?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="servicioEmpresa" class="span5 no-margin">Nombre de Empresa:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->servicioNombre->setAttrib('maxlength', '50')->renderViewHelper();?>
                                        <?php if ($this->form->servicioNombre->hasErrors()) echo "Ingrese Nombre de la Empresa";?>
                                    </div>

                                    <div class="clear"></div>
                                    <label for="servicioRuc" class="span5 no-margin">RUC:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->servicioRuc->setAttrib('maxlength', '12')->renderViewHelper();?>
                                        <?php if ($this->form->servicioRuc->hasErrors()) echo "Ingrese ruc";?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaInicio" class="span5 no-margin">Fecha de Inicio:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->fechaInicio->setAttrib('maxlength', '30')->renderViewHelper();?>
                                        <?php if ($this->form->fechaInicio->hasErrors()) echo "Ingrese fecha de inicio";?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaFin" class="span5 no-margin">Fecha de Fin:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->fechaFin->setAttrib('maxlength', '30')->renderViewHelper();?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="enCurso" class="span5 no-margin">En Curso:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->enCurso->setAttrib('maxlength', '30')->renderViewHelper();?>
                                    </div>
                                    
                                    
                                    
                                    <div class="clear"></div>
                                    <label for="montoTotal" class="span5 no-margin">Monto total S/. :</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->montoTotal->setAttrib('maxlength', '12')->renderViewHelper();?>
                                    </div>
                                    
                                   
                                </div>
                                <div class="clear"></div>

                            </div>
                            
                    </div>
                </div>
            </div>          
            </div>            
        </div>
        
        
        
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Persona de Referencia </h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span7">
                                    <div class="clear"></div>
                                    <label for="referenciaNombre" class="span5 no-margin">Nombre Completo:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->referenciaNombre->setAttrib('maxlength', '50')->renderViewHelper();?>
                                        <?php if ($this->form->referenciaNombre->hasErrors()) echo "Ingrese Nombre de referencia";?>
                                    </div>

                                    <div class="clear"></div>
                                    <label for="referenciaEmail" class="span5 no-margin">Email:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->referenciaEmail->setAttrib('maxlength', '50')->renderViewHelper();?>
                                        <?php if ($this->form->referenciaEmail->hasErrors()) echo "Ingrese Email de referencia";?>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="referenciaCargo" class="span5 no-margin">Cargo:</label>
                                    <div class="span4 no-margin">
                                        <?php echo $this->form->referenciaCargo->setAttrib('maxlength', '150')->renderViewHelper();?>
                                        <?php if ($this->form->referenciaCargo->hasErrors()) echo "Ingrese Cargo de la referencia";?>
                                    </div>

                                    <div class="clear"></div>
                                    <?php echo $this->form->csrf; ?>
                                    <?php if ($this->form->csrf->hasErrors()) echo "Intentalo nuevamente";?>
                                </div>
                                <div class="clear"></div>

                            </div>
                            <div class="form-actions">
                                <?php echo $this->form->guardar->setAttrib('class', 'btn pull-right')?>                    
                            </div> 
                    </div>
                </div>
            </div>          
            </div>            
        </div>
     </form>
    </div>
    
    <!--/span-->
</div>
<script>
$(document).ready(function(){    
    $("#fechaInicio").datepicker();
    $( "#fechaInicio" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    $("#fechaFin").datepicker();
    $( "#fechaFin" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
});
</script>