<div>
    <ul class="breadcrumb">
            <li>
                    <a href="/admin/procesos/criterios-seleccion">Criterios de Selección</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/procesos/criterios-evaluacion-personal/id/<?php echo $this->idEvaluacion;?>">Criterios de Evaluación el Personal</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/procesos/criterios-evaluacion-crear/id/<?php echo $this->idEvaluacion;?>">Agregar Criterio de Evaluación</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">

       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 20px;" aria-label="Status: activate to sort column ascending">
                                            IdCriterio
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Cargo
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Nivel Academico
                                        </th>
                                        <!--<th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Profesión
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Especialidad
                                        </th>-->
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 50px;" aria-label="Date registered: activate to sort column ascending">
                                            Sub Especialidad
                                        </th>
                                        
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 150px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php 
                                     foreach ($this->listaCriterioEvaluacion as $evaluacion):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $evaluacion['idCriterioEvaluacion'];?></td>
                                        <td class="center "><?php echo $evaluacion['cargo'];?></td>
                                        <td class="center "><?php echo $evaluacion['nivelAcademico'];?></td>
                                        <!--<td class="center "><?php //echo $evaluacion['profesion'];?></td>
                                        <td class="center "><?php //echo $evaluacion['especialidad'];?></td>-->
                                        <td class="center "><?php echo $evaluacion['subEspecialidad'];?></td>
                                        
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/procesos/criterios-evaluacion-editar/id/<?php echo $this->idEvaluacion;?>/idEvaluacion/<?php echo $evaluacion["idCriterioEvaluacion"]; ?>">
                                                <i class="icon-edit icon-white"></i>  
                                                Editar                                        
                                            </a>
                                            
                                            <a class="btn btn-danger" 
                                               href="/admin/procesos/criterios-evaluacion-eliminar/id/<?php echo $this->idEvaluacion;?>/idEvaluacion/<?php echo $evaluacion["idCriterioEvaluacion"]; ?>"
                                               onclick="return confirm('Seguro que desea eliminar el registro?')">
                                                <i class="icon-trash icon-white"></i>  
                                                Eliminar
                                            </a>
                                            
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>