create table `profesion`( `idProfesion` int(4) UNSIGNED NOT NULL AUTO_INCREMENT , `descripcion` char(60) CHARSET utf8 COLLATE utf8_spanish_ci NOT NULL , PRIMARY KEY (`idProfesion`))  ;
create table `especialidad`( `idEspecialidad` int(4) UNSIGNED NOT NULL AUTO_INCREMENT , `idProfesion` int(4) UNSIGNED NOT NULL , `descripcion` char(50) CHARSET utf8 COLLATE utf8_spanish_ci NOT NULL , PRIMARY KEY (`idEspecialidad`))  ;
create table `subespecialidad`( `idSubEspecialidad` int(4) UNSIGNED NOT NULL AUTO_INCREMENT , `idEspecialidad` int(4) UNSIGNED NOT NULL , `descripcion` char(50) CHARSET utf8 COLLATE utf8_spanish_ci NOT NULL , PRIMARY KEY (`idSubEspecialidad`))  ;


INSERT INTO profesion values (NULL, 'Abogado');
INSERT INTO profesion values (NULL, 'Administrador de empresas');
INSERT INTO profesion values (NULL, 'Administrador de Negocios Agropecuarios');
INSERT INTO profesion values (NULL, 'Administrador de Seguros');
INSERT INTO profesion values (NULL, 'Administrador en Turismo y Hotelería');
INSERT INTO profesion values (NULL, 'Administrador de Negocios Internacionales');
INSERT INTO profesion values (NULL, 'Antropólogo');
INSERT INTO profesion values (NULL, 'Arquitecto');
INSERT INTO profesion values (NULL, 'Asistente Social');
INSERT INTO profesion values (NULL, 'Bibliotecario');
INSERT INTO profesion values (NULL, 'Biólogo');
INSERT INTO profesion values (NULL, 'Bioquímico');
INSERT INTO profesion values (NULL, 'Catedrático Lengua y Literatura');
INSERT INTO profesion values (NULL, 'Contador');
INSERT INTO profesion values (NULL, 'Licenciado en Ciencias de la Comunicación');
INSERT INTO profesion values (NULL, 'Decoradora');
INSERT INTO profesion values (NULL, 'Diseñador Gráfico');
INSERT INTO profesion values (NULL, 'Diseñador Publicitario');
INSERT INTO profesion values (NULL, 'Docente');
INSERT INTO profesion values (NULL, 'Economista');
INSERT INTO profesion values (NULL, 'Estadístico');
INSERT INTO profesion values (NULL, 'Estudiante');
INSERT INTO profesion values (NULL, 'Fotógrafo');
INSERT INTO profesion values (NULL, 'Geólogo');
INSERT INTO profesion values (NULL, 'Historiador');
INSERT INTO profesion values (NULL, 'Licenciado en Idiomas');
INSERT INTO profesion values (NULL, 'Ing. Industrial');
INSERT INTO profesion values (NULL, 'Ing. Aeronáutico');
INSERT INTO profesion values (NULL, 'Ing. Agroindustrial');
INSERT INTO profesion values (NULL, 'Ing. Agrónomo');
INSERT INTO profesion values (NULL, 'Ing. Agrónomo Zootecnista');
INSERT INTO profesion values (NULL, 'Ing. Civil');
INSERT INTO profesion values (NULL, 'Ing. de Sistemas');
INSERT INTO profesion values (NULL, 'Ing. Electrónico');
INSERT INTO profesion values (NULL, 'Ing. Forestal');
INSERT INTO profesion values (NULL, 'Ing. Hidrólogo');
INSERT INTO profesion values (NULL, 'Ing. Mecánico');
INSERT INTO profesion values (NULL, 'Ing. Metalúrgico');
INSERT INTO profesion values (NULL, 'Ing. de Minas');
INSERT INTO profesion values (NULL, 'Ing. Naval');
INSERT INTO profesion values (NULL, 'Ing. Pesquero');
INSERT INTO profesion values (NULL, 'Ing. Quimico');
INSERT INTO profesion values (NULL, 'Ing. Textil');
INSERT INTO profesion values (NULL, 'Ing. Zootecnista');
INSERT INTO profesion values (NULL, 'Licenciado en Marketing');
INSERT INTO profesion values (NULL, 'Médico general');
INSERT INTO profesion values (NULL, 'Medico');
INSERT INTO profesion values (NULL, 'Veterinario');
INSERT INTO profesion values (NULL, 'Militar');
INSERT INTO profesion values (NULL, 'Militar (r)');
INSERT INTO profesion values (NULL, 'Nutricionista');
INSERT INTO profesion values (NULL, 'Periodista');
INSERT INTO profesion values (NULL, 'Psicólogo');
INSERT INTO profesion values (NULL, 'Psicólogo Clínico');
INSERT INTO profesion values (NULL, 'Publicista');
INSERT INTO profesion values (NULL, 'Químico Farmaceútico');
INSERT INTO profesion values (NULL, 'Lic. en Relaciones Industriales');
INSERT INTO profesion values (NULL, 'Lic. en Relaciones Internacionales');
INSERT INTO profesion values (NULL, 'Lic. en Relaciones Públicas');
INSERT INTO profesion values (NULL, 'Secretaria');
INSERT INTO profesion values (NULL, 'Secretaria Ejecutiva');
INSERT INTO profesion values (NULL, 'Secretaria Ejecutiva Bilingue');
INSERT INTO profesion values (NULL, 'Sociólogo');
INSERT INTO profesion values (NULL, 'Traductor');
INSERT INTO profesion values (NULL, 'Veterinario');
INSERT INTO profesion values (NULL, 'Zootecnista');

