<!-- Start: login-holder -->
<div id="login-holder">

	<!-- start logo -->
	<div id="logo-login">

	</div>
	<!-- end logo -->
	
	<div class="clear"></div>
	
	<!--  start loginbox ................................................................................. -->
	<div id="loginbox">
	
	<!--  start login-inner -->
	<div id="login-inner">
		<form  method="post">
		<table border="0" cellpadding="0" cellspacing="0">
		<tr>
                    <th colspan="2"><h1>Gracias por confirmar tu registro. <p></p> Ya puedes iniciar session</h1></th>
			
		</tr>
		<tr>
			<th></th>
			<td><input type="password"  id="clave"  name="clave"  class="login-inp" /></td>
		</tr>
		<tr>
			<th></th>
			<td valign="top">
                        </td>
		</tr>
		
		</table>
		</form>
	</div>
 	<!--  end login-inner -->
	<div class="clear"></div>
	
 <!--  end loginbox -->

</div>
<!-- End: login-holder -->
