<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Listado de convocatorias</a> <span class="divider">/</span>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">
        
       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            
                            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" 
                                   id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 30px;" aria-label="Status: activate to sort column ascending">
                                            Código
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Convocatoria
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Fecha Inicio
                                        </th>
                                        
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 80px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->lista as $experiencia):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $experiencia['codigo']?></td>
                                        <td class="center "><?php echo $experiencia['proceso']?></td>
                                        <td class="center "><?php echo $experiencia['fecha']?></td>                                        
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/convocatoria/paso1/id/<?php echo $experiencia["ID"]; ?>">
                                                <i class="icon-plus"></i>  
                                                Applicar Postulación
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>