<script type="text/javascript">
$(document).ready(function() {
	$("#modifica").validate({
            rules :{
                hora : {
                    required:true,
                    range : [0,23]
                },
                minuto : {
                    required:true,
                    range : [0,59]
                    
                },
                segu : {
                    required:true,
                    range : [0,59]
                }
            },
            messages : {
                hora : {
                    required : "Ingrese el dato",
                    range : "Ingrese hora valida"                                        
                },
                minuto : {
                    required : "Ingrese el dato",
                    range : "Ingrese hora valida"                    
                    
                },
                segu : {
                    required : "Ingrese el dato",
                    range : "Ingrese hora valida"                    
                    
                }
                
            }
            
        });
});


</script>
<div class="row-fluid sortable ui-sortable">
    
    <div class="box span12">
        <form name="modifica" id="modifica" action="" method="post" enctype="multipart/form-data" >
        <div class="box-header well" data-original-title="">
            <h2><i class="icon-user"></i> Actualización del Plazo</h2>
            <div class="box-icon">                
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>                
            </div>
        </div>
        <div class="box-content">
            <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                
                <div id="content">
                    <div class="inner">
                        <div class="well">
                            <div class="row-fluid">
                                <div class="span10">
                                    <div class="clear"></div>
                                    <label for="servicioEmpresa" class="span3 no-margin">Convocatoria:</label>
                                    <div class="span7 no-margin">
                                        <label><?php echo $this->convoca['proceso']?></label>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaInicio" class="span3 no-margin">Fecha Limite:</label>
                                    <div class="span7 no-margin">
                                        <input type="text" name="limite" id="fechaInicio" value="<?php echo $this->convoca['limite']?>"/>
                                    </div>
                                    
                                    <div class="clear"></div>
                                    <label for="fechaFin" class="span3 no-margin">Hora Limite:</label>
                                    <div class="span8 no-margin">
                                        <?php $hora = $this->convoca['hora_lim'];
 $a = explode(":", $hora);
                                                ?>
                                        <input type="text" size="1"  name="hora" id="fechaFin" value="<?php echo $a[0]?>" />:
                                        <input type="text" size="1" name="minuto" id="fechaFin" value="<?php echo $a[1]?>" />:
                                        <input type="text" size="1" name="segu" id="fechaFin" value="<?php echo $a[2]?>" />
                                        Formato 24h (HH : MM : SS)
                                    </div>
                                   
                                </div>
                                <div class="clear"></div>
                                <div class="form-actions">
                                <input type="submit" name="update" value="Actualizar" class="btn pull-right"/>
</div>
                            </div>
                            
                    </div>
                </div>
            </div>          
            </div>            
        </div>
        
     </form>
    </div>
    
    <!--/span-->
</div>
<script>    
$(document).ready(function(){    
    var fec = '<?php echo $this->fecha?>';    
    $("#fechaInicio").datepicker({
        "dateFormat" : "yy-mm-dd",        
        onClose: function( selectedDate ) {
            //fecha = selectedDate.split("-");
            fecha = fec.split("-");
            f = new Date(fecha[0], parseInt(fecha[1]) - 1, fecha[2]);
            $( "#fechaInicio" ).datepicker( "option", "minDate", f);
            //$( "#fechaFin" ).datepicker( "option", "minDate", f);
            //$( "#fechaInicio" ).val(selectedDate);
        }
    });
    $( "#fechaInicio" ).datepicker( "option", "dateFormat", "yy-mm-dd" );
    $( "#fechaInicio" ).val("<?=$this->convoca["limite"]?>");    
});
</script>