<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Listado de convocatorias</a> <span class="divider">/</span>
            </li>
    </ul>
</div>
<div class="row-fluid ui-accordion">		
    <div class="box span12">

       <div class="box-content">
            <div class="row-fluid">
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">                            
                            
                            
                            <table class="table table-striped table-header-options">
                                
                                <caption><strong><h3>Detalles Empresa</h3> </strong></caption>
                                <thead>
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50%; text-align: center" aria-label="Status: activate to sort column ascending">
                                            Código Empresa : <?php echo $this->empresa->idEmpresa?>
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 50%;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Empresa : <?php echo $this->empresa->nombreEmpresa?>
                                        </th>                                        
                                        
                                    </tr>
                                    <tr role="row">
                                        <th colspan="2" class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            style="text-align: center" aria-label="Status: activate to sort column ascending">
                                            Convocatoria : <?php echo $this->convocatoria['proceso']?>                                            
                                        </th>
                                    </tr>
                                </thead>   
                            </table>                            
                            <form method="post" enctype="multipart/form-data">
                            <table class="table table-striped table-bordered" 
                                   id="DataTables_Table_0">
                                
                                <caption style="padding-bottom: 30px"><strong><h4>Experiencia de la Empresa</h4> </strong></caption>                                
                                <thead>                                    
                                    <tr role="row">
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 30px;" aria-label="Status: activate to sort column ascending">
                                            Código
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Experiencia
                                        </th>
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Descripción
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 55px;" aria-label="Date registered: activate to sort column ascending">
                                            Seleccionar
                                        </th>                                        
                                        
                                    </tr>
                                </thead>   

                                <tbody>
                                     <?php foreach ($this->experiencia as $experiencia):
                                         
                                      ?>
                                    <tr>
                                        <td class="center"><?php echo $experiencia['idDetalleEmpresa']?></td>
                                        <td class="center "><?php echo $experiencia['servicioNombre']?></td>
                                        <td class="center "><?php echo $experiencia['descripcion']?></td>
                                        <td class="center" style="text-align: center"> 
                                            <input class="checkbox" type="checkbox" name="experiencia[]" id="experiencia" value="<?php echo $experiencia['idDetalleEmpresa']?>"/>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    
                                    </tbody>
                                    <tfoot>
                                        <tr>
                                            <td colspan="4" style="text-align: right">
                                                 <input type="submit" name="guardar" id="guardar" value="Siguiente" class="btn pull-right" />
                                            </td>
                                            
                                        </tr>
                                    </tfoot>
                            </table>
                                </form>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>