<div>
    <ul class="breadcrumb">
            <li>
                    <a href="#">Contacto</a> <span class="divider">/</span>
            </li>
            <li>
                    <a href="/admin/contacto/crear">Agregar Contacto</a>
            </li>
    </ul>
</div>
<div class="row-fluid sortable ui-sortable">		
    <div class="box span12">

       <div class="box-content">
            <div class="row-fluid sortable ui-sortable">		
                
                        <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper" role="grid">
                            <table class="table table-striped table-bordered bootstrap-datatable datatable dataTable" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 150px;" aria-sort="ascending" 
                                            aria-label="Username: activate to sort column descending">
                                            Nombre
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" 
                                            rowspan="1" colspan="1" style="width: 150px;" aria-label="Date registered: activate to sort column ascending">
                                            Apellido
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Cargo
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" 
                                            colspan="1" style="width: 150px;" aria-label="Role: activate to sort column ascending">
                                            Telefono
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1"
                                            colspan="1" style="width: 70px;" aria-label="Status: activate to sort column ascending">
                                            Estado
                                        </th>
                                        <th class="sorting" role="columnheader" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" c
                                            olspan="1" style="width: 170px;" aria-label="Actions: activate to sort column ascending">
                                            Accion
                                        </th>
                                    </tr>
                                </thead>   

                                <tbody role="alert" aria-live="polite" aria-relevant="all">
                                     <?php foreach ($this->listaContacto as $contacto):
                                         
                                      ?>
                                    <tr class="odd">
                                        <td class="  sorting_1"><?php echo $contacto['nombre']?></td>
                                        <td class="center "><?php echo $contacto['apellido']?></td>
                                        <td class="center "><?php echo $contacto['cargo']?></td>
                                        <td class="center "><?php echo $contacto['telefono']?></td>
                                        <td class="center ">
                                            <?php if ($contacto['estado'] == 1) : ?>
                                                <span class="label label-success">Activo</span>
                                            <?php endif; ?>
                                            <?php if ($contacto['estado'] == 0) : ?>
                                                <span class="label label-important">Eliminado</span>
                                            <?php endif; ?>
                                            
                                        </td>
                                        <td class="center ">
                                            <a class="btn btn-info" href="/admin/contacto/editar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-edit icon-white"></i>  
                                                Editar                                         
                                            </a>
                                            <a class="btn btn-danger" href="/admin/contacto/eliminar/id/<?php echo $contacto["idContacto"]; ?>">
                                                <i class="icon-trash icon-white"></i> 
                                                Eliminar
                                            </a>
                                        </td>
                                    </tr>
                                    <?php
                                    endforeach;
                                    ?>
                                    </tbody>
                            </table>
                            </div>            
                    
                <!--/span-->

            </div>         
        </div>
    </div><!--/span-->

</div>